### ISSUE TITLE
Довжина рядка не має бути  більшою за 80 символів згідно рекомендацій pep8

### ISSUE THREAD

**Issue by Muxamedin** [SBundev/home_works#2]
https://github.com/SBundev/home_works/blob/932deda6ba2fb936fc5e7e748535dd8e51d79138/hw_11/hw_11_4.py#L9
https://github.com/SBundev/home_works/blob/932deda6ba2fb936fc5e7e748535dd8e51d79138/hw_11/hw_11_4.py#L12

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/4419752/187755669-04bc517b-c568-471c-a8e5-199ee9021b27.png">

**Comment by SBundev** [comment]
![image](https://user-images.githubusercontent.com/109979924/187758510-6e6ee8f8-1139-4cdf-932f-83d378dd1d18.png)
Я не заметил, у меня не выдало ошибку.
Исправил
